Fixed get_template_sources
jptd/templated-docs pull request #5
Opened 2020-06-30 06:52 UTC by shinning91

Fixed `get_template_sources` to be compatible with Django 2.2.13
Refer: https://github.com/alexmorozov/templated-docs/pull/27/files

2020-06-30 08:03 UTC, shinning91 commented
@Jafnee travis fixed

2020-07-01 03:54 UTC, Jafnee requested changes

2020-07-01 03:54 UTC, Jafnee commented on setup.py
> +    'django>=1.8,<=2.2.13',
the change you made above to `MIDDLEWARE` was only introduced with Django 1.10.

For simplicity let's drop 'support' for Django 1.

Also 2.2.13 is too strict. We'd need to update this library after every DJ update. I recommend just set it to <3.0.0

2020-07-01 03:58 UTC, hueyyeng approved these changes
LGTM with the changes to requirements. Also can confirm with the removal of `None` argument, templated_docs can generate the PDF without issue.

2020-07-01 06:40 UTC, merged